### ISSUE TITLE
Controls glitched on Pre-Windows 10 versions

### ISSUE THREAD

**Issue by EugeneBadger** [SuchByte/Macro-Deck#145]
1:12:43 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Method not found: 'Windows.UI.Color Windows.UI.ViewManagement.UISettings.GetColorValue(Windows.UI.ViewManagement.UIColorType)'.
   at SuchByte.MacroDeck.GUI.Colors.get_WindowsAccentColorDark()
   at SuchByte.MacroDeck.GUI.CustomControls.ButtonPrimary.get_ProgressColor() in D:\Macro-Deck\Macro Deck 2\GUI\CustomControls\ButtonPrimary.cs:line 116
   at SuchByte.MacroDeck.GUI.CustomControls.ButtonPrimary.OnPaint(PaintEventArgs pe) in D:\Macro-Deck\Macro Deck 2\GUI\CustomControls\ButtonPrimary.cs:line 229
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam
![Скриншот 09-02-2022 011248](https://user-images.githubusercontent.com/99295153/153084550-bc34fe67-acd8-4cbd-aa83-2ab81afb2ff2.jpg)
![Скриншот 09-02-2022 011209](https://user-images.githubusercontent.com/99295153/153084556-89d4216e-e2b1-4380-a653-c58fd282a93c.jpg)
)

**Comment by SuchByte** [comment]
Please send the entire log file.
