### ISSUE TITLE
Creating new profile

### ISSUE THREAD

**Issue by PhoenixWyllow** [SuchByte/Macro-Deck#18]
Hi, 

Two issues I've found (v2b9). 
At first start you have a configuration wizard. I set the desk to 8 columns and 6 rows, but this wasn't set when completing the wizard. 
The profile was created as "Profile 1" so I tried creating a new profile (an Edit/Rename option would be nice if possible).
The two creation paths are quite different - the wizard allows basic grid setup, the New Profile option allows configuration of spacing, corner radius, etc. Is this intentional?

In any case, this was the error when I created the new profile:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Windows.Forms.TreeNodeCollection.get_Item(Int32 index)
   at SuchByte.MacroDeck.GUI.MainWindowContents.Deck.BtnAddProfile_Click(Object sender, EventArgs e) in C:\Users\Manuel\Nextcloud\Visual Studio Projects\Macro Deck 2\Macro Deck 2\GUI\MainWindowContents\Deck.cs:line 649
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.21.41101
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Private.CoreLib.dll
----------------------------------------
Macro Deck 2
    Assembly Version: 2.0.9.0
    Win32 Version: 2.0.9.0
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/Macro%20Deck%202.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.40306
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.InteropServices.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.Extensions.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Diagnostics.Process.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Linq.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Diagnostics.Debug.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.IO.FileSystem.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/Newtonsoft.Json.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/netstandard.dll
----------------------------------------
System.Console
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Console.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Threading.Thread.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Collections.dll
----------------------------------------
System.Memory
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Memory.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.2.2
    Win32 Version: 4.700.21.6905
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.40306
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/Accessibility.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.15.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Resources.ResourceManager.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.40306
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/System.Drawing.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Buffers.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Xml.XmlSerializer.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Private.Xml.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Collections.NonGeneric.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Text.RegularExpressions.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Reflection.Emit.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Private.Xml.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Reflection.Primitives.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Private.Uri.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 4.3.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Linq.Expressions.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.ObjectModel.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.ComponentModel.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/System.Windows.Extensions.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Threading.ThreadPool.dll
----------------------------------------
System.Net.NetworkInformation
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.NetworkInformation.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.Primitives.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.NameResolution.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Diagnostics.Tracing.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.WebClient.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.Numerics.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.Requests.dll
----------------------------------------
System.Security.Principal
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Principal.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.Http.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Threading.Tasks.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.ServicePoint.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Net.Security
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.Security.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Threading.Timer
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Threading.Timer.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Threading.Overlapped.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 4.1.3.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Security.Cryptography.Encoding.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 4.1.3.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/Microsoft.Win32.Registry.dll
----------------------------------------
System.IO.Compression.ZipFile
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.IO.Compression.ZipFile.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.IO.Compression.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Xml.ReaderWriter.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Reflection.Emit.Lightweight.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.700.21.41101
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Private.CoreLib.dll
----------------------------------------
SQLite-net
    Assembly Version: 1.7.335.0
    Win32 Version: 1.7.335.0
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/SQLite-net.dll
----------------------------------------
SQLitePCLRaw.core
    Assembly Version: 2.0.3.851
    Win32 Version: 2.0.3.851
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/SQLitePCLRaw.core.dll
----------------------------------------
SQLitePCLRaw.batteries_v2
    Assembly Version: 2.0.3.851
    Win32 Version: 2.0.3.851
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/SQLitePCLRaw.batteries_v2.dll
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    Assembly Version: 2.0.3.851
    Win32 Version: 2.0.3.851
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/SQLitePCLRaw.provider.dynamic_cdecl.dll
----------------------------------------
SQLitePCLRaw.nativelibrary
    Assembly Version: 2.0.3.851
    Win32 Version: 2.0.3.851
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/SQLitePCLRaw.nativelibrary.dll
----------------------------------------
Fleck
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Program%20Files/Macro%20Deck/Fleck.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.41608
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.41608
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/UIAutomationTypes.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.41608
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/WindowsBase.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.41608
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/UIAutomationProvider.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Diagnostics.StackTrace.dll
----------------------------------------
UIAutomationClientSideProviders
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.41608
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.19/UIAutomationClientSideProviders.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/3.1.19/System.IO.MemoryMappedFiles.dll
----------------------------------------

************** JIT Debugging **************
```

The new profile wasn't created it seems, but the grid did change. I still see "Profile 1" as the name. The grid now is 8x6, but the values in the lower right corner still say 5x3. Maybe all these things are connected to the error I got, but worth checking :)

**Comment by SuchByte** [comment]
I was able to fix all the issues and I removed the duplicate grid settings. :)
