### ISSUE TITLE
Crash on Button Delete

### ISSUE THREAD

**Issue by NightB1ade** [SuchByte/Macro-Deck#79]
**Describe the bug**
When attempting to delete buttons, I believe it's mainly buttons from previous version (2.3.2-dev), I get an error, then it does not delete.  In some cases the MacroDeck 2 program also crashes and will need restarting.

**To Reproduce**
1. Go to any screen, any button created in previous version 2.3.2-dev
2. Right-click
3. Delete

**Expected behavior**
Deletion of button, without error

**Screenshots**
```Macro Deck version: 2.4.0-dev
Windows version: Windows 10 Pro 64 bit

Object reference not set to an instance of an object.

   at SuchByte.MacroDeck.ActionButton.ActionButton.Dispose(Boolean disposing) in D:\Macro-Deck\Macro Deck 2\ActionButton\ActionButton.cs:line 58
   at SuchByte.MacroDeck.ActionButton.ActionButton.Dispose() in D:\Macro-Deck\Macro Deck 2\ActionButton\ActionButton.cs:line 77
   at SuchByte.MacroDeck.GUI.MainWindowContents.DeckView.ContextMenuDeleteItemClick(Object sender, EventArgs e) in D:\Macro-Deck\Macro Deck 2\GUI\MainWindowViews\DeckView.cs:line 447
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Additional context**
Previous version was 2.3.2-dev, buttons tested were "Open application" and "Hotkeys"x10 buttons

**Comment by SuchByte** [comment]
Fixed in version 2.4.1-dev.
